EBNF       ::=  EBNFL "." { EBNFL "." }.
EBNFL      ::=  Head "::=" Body { "|" Body }.
Head       ::=  Variable.
Body       ::=  Element { Element }.
Element    ::=  Terminal | Variable | "{" ElementOpt "}" | "[" ElementOpt "]".
ElementOpt ::=  Terminal [ ElementOpt ] | Variable { Element }.
Variable   ::=  @UPPERCASE [ ALPHANUMS ].
Terminal   ::=  "\"" STRING "\"".
ALPHANUMS  ::=  @ALPHANUM { @ALPHANUM }.
STRING     ::=  @PRINTABLE { @PRINTABLE }.