name: Haskell CI
on: 
  push:
    branches: ["main"]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.6.6'
          # cabal-version: 'latest'. Omitted, but defaults to 'latest'
          enable-stack: true
          stack-version: '3.1.1'
      - name: Install dependencies
        run: stack --system-ghc build --no-run-tests
      - name: Run tests
        run: stack --system-ghc test